apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: time-learning-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/surfjoan/ios-apps.git
    targetRevision: HEAD
    path: time-learning-app/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: time-learning
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
